apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: redis-cart
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - redis-cart.hipstershop-staging.demo1.keptn.live.demo.dynatrace.com
  - redis-cart
  http:
  - route:
    - destination:
        host: redis-cart-canary.hipstershop-staging.svc.cluster.local
    - destination:
        host: redis-cart-primary.hipstershop-staging.svc.cluster.local
      weight: 100
