apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: recommendationservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - recommendationservice.hipstershop-staging.demo1.keptn.live.demo.dynatrace.com
  - recommendationservice
  http:
  - route:
    - destination:
        host: recommendationservice-canary.hipstershop-staging.svc.cluster.local
      weight: 100
    - destination:
        host: recommendationservice-primary.hipstershop-staging.svc.cluster.local
